### ISSUE TITLE
Fix type errors

### ISSUE THREAD

**Issue by neonfuz** [bismuthsoft/fmsite#11]
Running `pnpm run check` currently gives 37 errors and 5 hints

**Comment by neonfuz** [comment]
Lets both fix the errors in the files we made so we don't have overlapping commits

**Comment by 44100hertz** [comment]
OK

**Comment by neonfuz** [comment]
It's pretty inconsequential but when you added this you should have passed `-D` like `pnpm add -D @types/audioworklet` to add it as a development dependency instead of a runtime dependency. You can edit package.json to move it from dependencies to devDependencies (in alphabetical order, fix commas because json is pickier than js) and run `pnpm i` to regenerate the lockfile.

**Comment by 44100hertz** [comment]
This issue is going to keep coming up until I somehow get editor integration for typescript svelte

**Comment by 44100hertz** [comment]
Part of the problem is the worklet types work when "lib": { "esnext" } is added to tsconfig.json, but this causes other DOM types to no longer be recognized. Is there a way to do a localized tsconfig.json which applies only to the worklet files?

**Comment by neonfuz** [comment]
I have typescript types working in my editor so I think this is a problem with your editor not the codebase.

I think we can fix the remaining errors and close this issue soon. I don't know which errors you're referring to with esnext. The last 4 errors which are quite big are about a missing size parameter on the knobs.
