### ISSUE TITLE
Polyphony

### ISSUE THREAD

**Issue by neonfuz** [bismuthsoft/fmsite#12]

**Comment by 44100hertz** [comment]
Restructuring for polyphony is WIP.

1. Control logic moved from SoundGenController to Mixer, which then controls any number of Voices. SoundGenController will be renamed to reflect its new role as a simple wrapper for the worker. This makes the web worker more high level, but this improves architecture simplicity -- fewer types, fewer conversions.
2. Universal "parameters" are now particular "instruments" which are stored in a bank. Instruments are stateless, they simply tell the mixer how to configure each voice.
3. SetParams is now SetInstrument, and there is also the NoteUp and NoteDown commands.

**Comment by 44100hertz** [comment]
Another thing: Splitting each instrument configuration into its own panel separate from ControlPanel.

**Comment by 44100hertz** [comment]
OK. Polyphony has been implemented.
