### ISSUE TITLE
Knob Data Entry bugs

### ISSUE THREAD

**Issue by 44100hertz** [bismuthsoft/fmsite#14]
1. The piano grabs inputs from this when trying to type numbers. I can try to fix the problem...?
2. Can enter non-numbers and break the knob

Proposed solution: disable the data entry feature until a future version.

**Comment by neonfuz** [comment]
This is 2 issues and number 2 should be on the svelte-dj-knob repo

**Comment by neonfuz** [comment]
Opened https://github.com/bismuthsoft/svelte-dj-knob/issues/3.

I'm closing this issue because we have separate issues for each of these now.
