### ISSUE TITLE
Oscilloscope

### ISSUE THREAD

**Issue by 44100hertz** [bismuthsoft/fmsite#3]
By using the Voice module running at a low sample rate, called periodically, generate an elegant preview of the currently playing wave displayed using SVG+CSS. Display this adjacent to each oscillator.

**Comment by neonfuz** [comment]
I like it, though when the wave gets really dense it's hard to see it's shape. Probably no easy solution but just a thought for a future improvement.

**Comment by 44100hertz** [comment]
When the wave gets overly dense, it also sounds like noise.
