### ISSUE TITLE
No sound on Chrome mobile

### ISSUE THREAD

**Issue by 44100hertz** [bismuthsoft/fmsite#36]

**Comment by neonfuz** [comment]
I'm getting sound on chrome now, however sometimes it seems to fail to initialize? And it can "crash" easily. I think android has some sort of audio focus system, when I tried to record with the system screen recorder the sound failed. Also I couldn't get it working while playing a youtube video in the background.

**Comment by neonfuz** [comment]
My guess is there's more to the audio worklet api, might have to re capture focus after it's lost?

**Comment by neonfuz** [comment]
Related bug with wontfix:

https://bugs.chromium.org/p/chromium/issues/detail?id=835208

**Comment by neonfuz** [comment]
Possible solution would be to grab pointer capture and then release it, untested.

**Comment by 44100hertz** [comment]
Implemented hack solution. Resume worklet on key up. Good enough for now.
