### ISSUE TITLE
Volume knob from -72dB to 0dB is backwards.

### ISSUE THREAD

**Issue by 44100hertz** [bismuthsoft/fmsite#8]
This is an isssue in the DJ Knob module.

**Comment by neonfuz** [comment]
This issue is in the DumbKnob component you wrote so actually you should fix this

**Comment by neonfuz** [comment]
Volume knob is gone, but the MinimalKnob still draws backwards, even after the rebase.

**Comment by neonfuz** [comment]
Closing because the issue is on the wrong repo.
